services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "8080:80"
    networks:
      - app-network

  php:
    build:
      context: .
    container_name: php-container
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "80:80"

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
